"""
Reporting Module: Formatting and Exporting Biophysical Run Analyses and Predictions.
Outputs clean GitHub-flavored Markdown tables and CSV data.
"""

import csv
from typing import Dict, Any, List, Optional
from stasispath.f3_ischemia import tau_eq
from stasispath.f4_nucleation import t_max_nucleation
from stasispath.f5_cooling import validate_cooling_profile
from stasispath.thermal_stress import fracture_risk
from stasispath.cpa_toxicity import predicted_ocr_retention
from stasispath.domains import check_domain_limits


def generate_protocol_report(
    organ_name: str,
    mass_kg: float,
    V_L: float,
    lc_cm: float,
    cpa: str = "M22",
    loading_temp_c: float = -22.0,
    loading_time_min: float = 25.0,
    cooling_profile: Optional[Dict[str, List[float]]] = None,
) -> str:
    """
    Generates a structured Markdown assessment report for a proposed laboratory protocol.

    Args:
        organ_name: Descriptive name (e.g. 'Porcine Kidney', 'Human Liver Wedge').
        mass_kg: Mass in kilograms.
        V_L: Volume in Liters.
        lc_cm: Characteristic conduction half-thickness in cm.
        cpa: Selected CPA mixture.
        loading_temp_c: Temperature during subzero CPA perfusion.
        loading_time_min: Exposure time in CPA solution.
        cooling_profile: Dict with 'times_min' and 'temps_c'.

    Returns:
        Markdown report string.
    """
    domain = check_domain_limits(mass_kg, loading_temp_c, species="mammalian")
    tox = predicted_ocr_retention(loading_temp_c, loading_time_min, cpa=cpa)
    t_nuc = t_max_nucleation(V_L)
    risk_tg = fracture_risk(0.150, lc_cm)

    md = []
    md.append(f"# STASISPATH PROTOCOL EVALUATION REPORT")
    md.append(f"**Target System:** {organ_name} ({mass_kg:.3f} kg, {V_L:.3f} L, $LC = {lc_cm:.2f}\\text{{ cm}}$)")
    md.append(f"**CPA Selected:** `{cpa}` at {loading_temp_c:.1f} °C for {loading_time_min:.1f} min\n")

    md.append("## 1. Domain Feasibility & Epistemic Boundary")
    md.append(f"- **Ontological Status:** `{domain['whole_body_state'].value}`")
    if domain["warnings"]:
        md.append("- **Active Warnings:**")
        for w in domain["warnings"]:
            md.append(f"  * {w}")
    md.append("")

    md.append("## 2. Quantitative Thermodynamic Metrics")
    md.append("| Metric | Value | Constraint / Target | Status |")
    md.append("|---|---|---|---|")
    md.append(f"| **Predicted OCR Retention** | {tox['predicted_ocr_percent']:.1f} % | $\\ge 85\\text{{ %}}$ (P19 Target) | `{tox['status']}` |")
    md.append(f"| **Predicted Damage ($D_{{CPA}}$)** | {tox['d_cpa']:.3f} | $\\le 0.150$ | `{'PASS' if tox['d_cpa'] <= 0.150 else 'FAIL'}` |")
    md.append(f"| **Stochastic Nucleation Limit ($t_{{max}}$)** | {t_nuc:.2f} h ({t_nuc * 60:.1f} min) | $V \\cdot t \\approx 1.0\\text{{ L}}\\cdot\\text{{h}}$ | `UNFREEZING WINDOW` |")
    md.append(f"| **Thermomechanical Stress at $T_g$** | {risk_tg['sigma_thermal_mpa']:.2f} MPa | $\\le 2.0\\text{{ MPa}}$ | `{risk_tg['risk_level']}` |")
    md.append("")

    if cooling_profile:
        profile_res = validate_cooling_profile(
            cooling_profile["times_min"],
            cooling_profile["temps_c"],
            cpa=cpa,
        )
        md.append("## 3. Cooling Trajectory Validation")
        md.append(f"- **Verdict:** `{'VALID' if profile_res['valid'] else 'INVALID'}`")
        md.append(f"- **Summary:** {profile_res['summary']}")
        if profile_res["violations"]:
            for v in profile_res["violations"]:
                md.append(f"  * ⚠️ {v}")
        md.append("")

    md.append("---")
    md.append("*Generated by StasisPath Toolkit v0.1.0 — StasisPath Framework (2026).*")
    return "\n".join(md)


def export_predictions_csv(predictions: List[Dict[str, Any]], filepath: str) -> None:
    """
    Exports a list of prediction evaluation dictionaries to CSV.

    Args:
        predictions: List of dicts returned by eval_p19 / eval_h2..eval_h5.
        filepath: Destination file path.
    """
    if not predictions:
        return

    keys = set()
    for p in predictions:
        keys.update(p.keys())
    fieldnames = sorted(list(keys))

    with open(filepath, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for p in predictions:
            # Flatten non-primitive items to string
            row = {k: str(v) if not isinstance(v, (int, float, bool, str)) else v for k, v in p.items()}
            writer.writerow(row)
