"""StasisPath: gaps to human. Cross-species triangulation + generalized rule of three.

Called by motor.py: generar(D, PAR, R, ROOT) writes BRECHAS.md and red/fig/B_brechas.png.
For each section: it projects every animal observation to human with that section's scaling law,
triangulates (n independent species, median or best value, spread), measures how many orders of
magnitude remain and converts them to %. Each route to the goal is evaluated by its bottleneck
(law of the minimum): all sections are necessary at once.
"""
import math, statistics
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SURF, INK, INK2, MUTED, GRID, BLUE, ORANGE = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#2a78d6", "#eb6834"

def g(x): return f"{x:.3g}" if abs(x) < 1e4 else f"{x:,.0f}"
def tabla(filas, cab):
    return "| " + " | ".join(cab) + " |\n|" + "---|" * len(cab) + "\n" + "\n".join(
        "| " + " | ".join(str(c) for c in f) + " |" for f in filas) + "\n"

def generar(D, PAR, R, ROOT):
    Mh = D["humano"]["masa"]
    res = {}
    for bid, b in D["brechas"].items():
        meta = b["meta"]
        if isinstance(meta, str):                       # goal computed from a bound of the network
            c, o = meta.split("."); meta = R[c]["out"][o]
        proy = []
        for o in b["obs"]:
            vh = o["v"] * (Mh / o["M"]) ** o["b"]
            proy.append({**o, "vh": vh})
        F = {"max": max, "min": min, "mediana": statistics.median}[b["agregado"]]
        firmes = [p for p in proy if not p.get("disputado")]
        vals = [p["vh"] for p in (firmes or proy)]
        agg = F(vals)
        agg_con = F([p["vh"] for p in proy])
        hay_disp = len(firmes) < len(proy)
        esp = {p["e"].split(" (")[0] for p in proy}
        if b["modo"] == "mayor":
            rest = max(0.0, math.log10(meta / agg)); logr = math.log10(agg / b["base"])
        else:
            rest = max(0.0, math.log10(agg / meta)); logr = math.log10(b["base"] / agg)
        logr = max(logr, 0.0)
        pct = 100.0 if rest == 0 else 100 * logr / (logr + rest)
        if b["modo"] == "mayor":
            rest_c = max(0.0, math.log10(meta / agg_con)); lg_c = max(math.log10(agg_con / b["base"]), 0.0)
        else:
            rest_c = max(0.0, math.log10(agg_con / meta)); lg_c = max(math.log10(b["base"] / agg_con), 0.0)
        pct_con = 100.0 if rest_c == 0 else 100 * lg_c / (lg_c + rest_c)
        res[bid] = dict(b=b, meta=meta, proy=proy, agg=agg, rest=rest, pct=pct, n=len(esp),
                        hay_disp=hay_disp, agg_con=agg_con, pct_con=pct_con, rest_con=rest_c,
                        disp=(max(vals) / min(vals)) if min(vals) > 0 else float("inf"))

    # routes: law of the minimum
    rutas = {}
    for via, nom in (("fisica", "Physical route (vitrification → years)"), ("biologica", "Biological route (torpor → months to 1 year)")):
        ids = [k for k, r in res.items() if via in r["b"]["via"]]
        cuello = min(ids, key=lambda k: res[k]["pct"])
        gm = math.exp(sum(math.log(max(res[k]["pct"], 1)) for k in ids) / len(ids))
        rutas[via] = dict(nom=nom, ids=ids, cuello=cuello, gm=gm)

    # nanowarming power by linear rule of three (note to B6)
    pot70 = 120 * (Mh / 1000 / 2) * (PAR["CWR_M22"]["v"] / PAR["nano_rate"]["v"])

    # ---- figura
    orden = sorted(res, key=lambda k: res[k]["pct"])
    fig, ax = plt.subplots(figsize=(8.5, 0.42 * len(orden) + 1.4))
    ys = range(len(orden))
    cuellos = {r["cuello"] for r in rutas.values()}
    for y, k in zip(ys, orden):
        r = res[k]
        ax.barh(y, 100, color=GRID, height=0.55, zorder=1)
        ax.barh(y, r["pct"], color=ORANGE if k in cuellos else BLUE, height=0.55, zorder=2)
        ax.text(min(r["pct"], 100) + 1.2, y, f"{r['pct']:.0f} %" + (f" · {r['rest']:.1f} orders of magnitude remaining" if r["rest"] > 0 else " · alcanzado"),
                va="center", fontsize=7.5, color=INK2)
    ax.set_yticks(list(ys)); ax.set_yticklabels([f"{k} · " + (res[k]['b']['nombre'] if len(res[k]['b']['nombre']) <= 46 else res[k]['b']['nombre'][:45] + "…") for k in orden], fontsize=7.5, color=INK2)
    ax.set_xlim(0, 135); ax.set_xticks([0, 25, 50, 75, 100]); ax.set_xlabel("% of the distance to human (logarithmic scale, orders of magnitude)")
    for s in ("top", "right", "left"): ax.spines[s].set_visible(False)
    ax.grid(axis="y", visible=False); ax.set_facecolor(SURF); fig.set_facecolor(SURF)
    fig.suptitle("Gaps to human by section\norange = bottleneck of a route (physical: B8 · biological: B10m)", x=0.02, ha="left", fontsize=11, color=INK)
    fig.tight_layout(); fig.savefig(ROOT / "red" / "fig" / "B_brechas.png", dpi=150); plt.close(fig)

    # ---- documento
    doc = ("<!-- AUTO-GENERATED by red/brechas.py (called from red/motor.py). DO NOT EDIT BY HAND. -->\n"
           "# StasisPath: gaps to human (triangulation + generalized rule of three)\n\n"
           "**What this measures and what it does not:** the *framework's* grounding (knowledge) is in MARCO.md. Here we measure **how much technological distance remains to the human goal** "
           "in each section. The framework can reach 100 % (knowing exactly what is missing and why) with the technology still far away.\n\n"
           "**Method:** each animal datum is projected to human with the section's scaling law, v_h = v·(M_h/M)^b: b = 0 invariant (τ_eq, time below Tg), "
           "b = 1 linear (energy, power), b = 0.25 Kleiber (reserve autonomy). The *linear* rule of three is used only where the physics is linear: "
           "scaling the cooling of a rat kidney (1.5 g) to 70 kg with a linear rule of three would give a rate ~36 times lower than the correct one (M^−2/3). "
           "% = orders achieved / (achieved + remaining), with the base declared on each row. **Triangulation:** n = independent species or systems (n < 3 ⇒ weak).\n\n")
    doc += "![Gaps](red/fig/B_brechas.png)\n\n## Routes to the goal (law of the minimum: every section at once)\n\n"
    for via, rt in rutas.items():
        c = res[rt["cuello"]]
        doc += (f"- **{rt['nom']}:** bottleneck **{rt['cuello']} · {c['b']['nombre']}** at **{c['pct']:.0f} %** "
                f"({c['rest']:.1f} orders of magnitude remaining). Geometric mean of its sections: {rt['gm']:.0f} %.\n")
    doc += "\n## Apartados\n\n"
    filas = []
    for k in sorted(res, key=lambda k: res[k]["pct"]):
        r = res[k]; b = r["b"]
        marca = f" · with disputed: {g(r['agg_con'])} → {r['pct_con']:.0f} %" if r["hay_disp"] else ""
        filas.append([k, b["nombre"], f"{g(r['meta'])} {b['u']}", f"{g(r['agg'])} ({b['agregado']}){marca}", f"{r['rest']:.2f}",
                      f"**{r['pct']:.0f} %**", f"{r['n']}" + (" ⚠ weak" if r["n"] < 3 else ""), g(b["base"])])
    doc += tabla(filas, ["id", "section", "human goal", "triangulated projection", "orders remaining", "% of path", "n", "base"])
    doc += "\n## Projection detail (animal → human)\n\n"
    for k in sorted(res):
        r = res[k]; b = r["b"]
        doc += f"### {k} · {b['nombre']}\n"
        if b.get("nota"): doc += b["nota"].replace("{pot70}", f"{pot70:.0f}") + "\n\n"
        doc += tabla([[p["e"], g(p["v"]), g(p["M"]), p["b"], g(p["vh"]), p["f"]] for p in r["proy"]],
                     ["observation", f"value ({b['u']})", "mass g", "exponent b", "projected to human", "source"])
        doc += f"Triangulation spread: ×{g(r['disp'])} between the largest and the smallest projection.\n\n"
    doc += ("## How to attack the holes\n\nOrdered by **orders of magnitude remaining** (the largest is the most limiting):\n\n" +
            "\n".join(f"{i+1}. **{k}** ({res[k]['rest']:.1f} orders): {res[k]['b']['nombre']}" for i, k in
                      enumerate(sorted([k for k in res if res[k]["rest"] > 0], key=lambda k: -res[k]["rest"]))) + "\n")
    (ROOT / "BRECHAS.md").write_text(doc)
    return res, rutas
