"""StasisPath: automatic analysis of P21 (the cooling-law exponent).

Applies LITERALLY the rules frozen in preregistration P21. It has no adjustable parameters:
the thresholds (2.34, 5.3, control 1.4 ± 15 %) are read from the frozen text and the hash protects them (R2).
With `mediciones_P21: []` it reports 'awaiting data'. Output: P21.md. Called by motor.py.
"""
import math

UMBRAL_N, CCR_VMP, CTRL, CTRL_TOL = 2.34, 5.3, 1.4, 0.15
F2 = [(1.2, 1.4), (1.402, 0.998), (2.2, 0.47)]   # (LC cm, °C/min): the three published volumes
T95U = {1: 6.314, 2: 2.920, 3: 2.353, 4: 2.132, 5: 2.015, 6: 1.943, 7: 1.895, 8: 1.860, 9: 1.833, 10: 1.812,
        12: 1.782, 15: 1.753, 20: 1.725, 30: 1.697}

def _t(gl):
    return T95U[max(k for k in T95U if k <= gl)]

def analizar(meds):
    """meds: list of {vol_L, V_mL, A_cm2, tasa}. Returns a dict with the verdict and the numbers."""
    ctrl = [m for m in meds if abs(m["vol_L"] - 0.5) < 1e-9]
    nuevas = [m for m in meds if abs(m["vol_L"] - 0.5) >= 1e-9]
    if not meds:
        return {"estado": "PENDING", "motivo": "no data: the experiment has not been executed"}
    if not ctrl:
        return {"estado": "NO INTERPRETABLE", "motivo": "the 0.5 L control bag is missing"}
    c = sum(m["tasa"] for m in ctrl) / len(ctrl)
    if abs(c / CTRL - 1) > CTRL_TOL:
        return {"estado": "NO INTERPRETABLE", "motivo": f"0.5 L control = {c:.3g} °C/min, outside 1.4 ± 15 %: the rig is not the one in F2"}
    grupos = {}
    for m in nuevas:
        grupos.setdefault(m["vol_L"], []).append((m["V_mL"] / m["A_cm2"], m["tasa"]))
    pts = [(math.log(L), math.log(r)) for L, r in F2] + [(math.log(L), math.log(r)) for g in grupos.values() for L, r in g]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    k = len(xs); mx, my = sum(xs) / k, sum(ys) / k
    sxx = sum((x - mx) ** 2 for x in xs)
    b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx
    n = -b
    gl = sum(len(g) - 1 for g in grupos.values())
    if gl >= 1:   # pure error of the replicates, as P21 fixes
        ss = sum(sum((math.log(r) - sum(math.log(q) for _, q in g) / len(g)) ** 2 for _, r in g) for g in grupos.values())
    else:         # without replicates: residuals of the fit (P21 does not foresee this; it is reported, but penalizes)
        a = my - b * mx; ss = sum((y - (a + b * x)) ** 2 for x, y in zip(xs, ys)); gl = k - 2
    se = math.sqrt(ss / gl) / math.sqrt(sxx)
    sup, inf = n + _t(gl) * se, n - _t(gl) * se
    nvol = 3 + len(grupos)
    peq = [r for v, g in grupos.items() if v <= 0.3 for _, r in g]
    directa = (sum(peq) / len(peq)) if peq else None
    if directa is not None and directa >= CCR_VMP:
        est, mot = "FAIL", f"direct check: small bags at {directa:.3g} °C/min ≥ CCR of VMP"
    elif sup < UMBRAL_N:
        est, mot = "PASS", f"95 % upper bound on n = {sup:.3g} < {UMBRAL_N}"
    elif nvol >= 4 and inf > UMBRAL_N:
        est, mot = "FAIL", f"95 % lower bound on n = {inf:.3g} > {UMBRAL_N}: C3 refuted"
    else:
        est, mot = "INCONCLUSO", f"n = {n:.3g}, IC unilateral [{inf:.3g}, {sup:.3g}] contiene {UMBRAL_N}"
    return {"estado": est, "motivo": mot, "n": n, "se": se, "gl": gl, "sup": sup, "inf": inf,
            "nvol": nvol, "control": c, "directa": directa, "grupos": grupos}

def generar(D, ROOT):
    r = analizar(D.get("mediciones_P21") or [])
    doc = ("<!-- AUTO-GENERATED by red/p21.py. DO NOT EDIT BY HAND. -->\n"
           "# P21: the cooling-law exponent — experiment status\n\n"
           f"**Estado: {r['estado']}** — {r['motivo']}.\n\n"
           "Rules (frozen in preregistration P21, hash-protected): PASSES if the one-sided 95 % upper bound on n < 2.34; "
           "FAILS if the lower bound > 2.34 or if the ~0.15 L bags cool at ≥ 5.3 °C/min; otherwise inconclusive. "
           "Control: 0.5 L debe dar 1.4 °C/min ± 15 %.\n\n")
    if r["estado"] == "PENDING":
        doc += ("**How to load a datum:** one line per bag in `mediciones_P21` of `red/stasispath.yaml` "
                "(`{vol_L, V_mL, A_cm2, tasa}`) then `python3 red/motor.py`. The verdict comes out on its own.\n\n"
                "**Preregistered design (B'):** 1 control bag of 0.5 L + 3 bags of ~0.15 L + 3 bags of ~7 L, rig identical to F2.\n")
    elif "n" in r:
        doc += (f"| quantity | value |\n|---|---|\n| fitted n | {r['n']:.3f} ± {r['se']:.3f} ({r['gl']} dof) |\n"
                f"| one-sided 95 % bound | [{r['inf']:.3f}, {r['sup']:.3f}] |\n| volumes | {r['nvol']} |\n"
                f"| control 0.5 L | {r['control']:.3g} °C/min |\n"
                + (f"| direct rate ~0.15 L | {r['directa']:.3g} °C/min |\n" if r['directa'] is not None else ""))
    (ROOT / "P21.md").write_text(doc)
    return r
