"""StasisPath: conditional projection to closure. The two bells.

Project two distributions — what we HAVE and what we NEED — and see how the framework would
stand once closed.

**Declared, non-negotiable limit:** this does NOT raise the real percentage. The framework stays
where it is until somebody measures. What is computed here is a **conditional scenario**: 'if every
prediction is confirmed, the framework would stand like this'. A scenario is not an achievement, and
it is labelled as such on every line. Letting the code round itself up would be fabricating progress.

What it does contribute, and it is a great deal: it makes the framework **entirely falsifiable**. Each
prediction carries its value, its dispersion and **what result would refute it**. When the datum
arrives, the module compares and warns if it falls outside — that is the real self-correction.
"""
import math

def g(x):
    if x is None or x != x: return "—"
    return f"{x:.3g}" if abs(x) < 1e4 else f"{x:,.0f}"

def tabla(f, cab):
    return "| " + " | ".join(cab) + " |\n|" + "---|" * len(cab) + "\n" + "\n".join(
        "| " + " | ".join(str(c) for c in r) + " |" for r in f) + "\n"

# What we NEED: the framework's prediction for each open node, with dispersion and refutation.
# sigma_rel = relative dispersion (1σ) that the framework assigns to its own prediction.
PREDICHO = [
    # id, what it is, predicted value, unit, sigma_rel, where it comes from, what REFUTES it
    ("I1", "damage in the cold arm of P19", 0.142, "", 0.55, "Arrhenius × German's point (DERIVACION)",
     "a damage > 0.25 refutes the derivation; > 0.22 would additionally make P19 fail"),
    ("I2", "CCR of the eutectic solvents", 0.3, "°C/min", 1.20, "upper bound by immersion + ordering of known CPAs",
     "a CCR > 0.426 leaves the human brain out and forces P19 to be executed"),
    ("I4", "human τ_eq with optimal reperfusion", 17.0, "min", 0.45, "cross-species invariance (T1 of the scaling)",
     "a value < 12.5 min would refute the invariance; > 60 min would contradict Hossmann's cat"),
    ("I5", "Nucleation J at −6 °C", 0.57, "/L·h", 0.50, "fit to the two rat-liver points",
     "a J > 0.85 prevents reaching 4 h at 95 % in human liver"),
    ("X2", "does chemistry solve the bottleneck?", 1.0, "verdict", 0.0, "B1: both paths predict PASS",
     "P19 yielding LTP ≤ 110 % with a valid positive control"),
]

def generar(D, PAR, DERIV, ROOT, total_actual, rumbo=None):
    # ---- Bell 1: what we HAVE. Relative dispersion of each verified parameter.
    tengo = []
    for k, v in PAR.items():
        lo, hi = v["r"]; c = v["v"]
        if c and lo > 0 and hi > lo:
            tengo.append((k, (hi - lo) / (2 * c)))     # semiancho relativo ≈ 1σ
    tengo.sort(key=lambda t: t[1])
    rel_t = [x[1] for x in tengo]
    med_t = rel_t[len(rel_t) // 2]

    # ---- Bell 2: what we NEED.
    rel_n = sorted(p[4] for p in PREDICHO if p[4] > 0)
    med_n = rel_n[len(rel_n) // 2]

    filas_n = [[i, q, f"{g(v)} {u}", f"±{g(s*100)} %", src, ref] for i, q, v, u, s, src, ref in PREDICHO]

    # ---- Conditional scenario: the framework IF all predictions are confirmed
    #      The engine is not touched: it is computed separately and labelled as a scenario.
    # The points are NOT written by hand: they are simulated with red/rumbo.py (same propagation rule as the engine).
    # There used to be constants here (X2 = +5.95) that turned out to be optimistic by ~3 points (batch 44).
    CADENA_I2 = ["X2", "V26", "F80"]                 # NADES: the measured CCR closes X2 and its pathway
    CADENA_I5 = ["L41", "V27", "F85", "F22"]         # fitted nucleation: supercooling
    sim = rumbo["simular"]
    pts_x2 = sim(CADENA_I2) - total_actual
    pts_resto = sim(CADENA_I2 + CADENA_I5) - total_actual - pts_x2
    proy = total_actual + pts_x2 + pts_resto
    irreducible = 100 - proy
    techo_todo = rumbo["techo"]

    doc = ("<!-- AUTO-GENERATED by red/proyeccion.py. DO NOT EDIT BY HAND. -->\n"
           "# StasisPath: conditional projection to closure\n\n"
           "> **This is NOT progress.** The framework stands at "
           f"**{total_actual:.1f} %** and stays there until somebody measures. What follows is a "
           "**conditional scenario**: how it would stand *if* every prediction is confirmed. A scenario is not an achievement. "
           "Letting the code round itself up to 100 % would be fabricating progress, which is why it is not done.\n\n"
           "What it does contribute: **it makes the framework entirely falsifiable**. Every prediction carries a value, a dispersion and "
           "**what result would refute it**.\n\n"
           "## Las dos campanas\n\n"
           + tabla([["**what we have**", f"{len(tengo)} verified parameters", f"±{g(med_t*100)} %",
                     f"from ±{g(min(rel_t)*100)} % to ±{g(max(rel_t)*100)} %"],
                    ["**what we need**", f"{len(rel_n)} predicciones abiertas", f"±{g(med_n*100)} %",
                     f"from ±{g(min(rel_n)*100)} % to ±{g(max(rel_n)*100)} %"]],
                   ["bell", "n", "median dispersion", "range"]) +
           f"\n**What the comparison says:** what we already have is measured with a median dispersion of "
           f"**±{g(med_t*100)} %**; what is missing we predict to **±{g(med_n*100)} %**, that is "
           f"**{g(med_n/med_t)} times wider**. ⇒ **There is no need to measure better than we already measure**: it suffices to "
           "measure what is missing **to the same quality** as what is already there, and the framework closes.\n\n"
           "## What the framework predicts, and what refutes it\n\n"
           + tabla(filas_n, ["id", "quantity", "prediction", "±1σ", "where it comes from", "what REFUTES it"]) +
           "\n## Closure scenario (conditional, not achieved)\n\n"
           + tabla([["Estado real hoy", f"{total_actual:.1f} %", "measured"],
                    ["If the eutectic-solvent CCR is confirmed (closes X2, V26, F80)", f"+{pts_x2:.1f}", "**escenario simulado**"],
                    ["If I5 is also confirmed (L41, V27, F85, F22)", f"+{pts_resto:.1f}", "**escenario simulado**"],
                    ["**Ceiling of the prediction scenario**", f"**{proy:.1f} %**", "**escenario simulado**"],
                    ["Not covered by any prediction", f"{irreducible:.1f} %", "secondary sources and pathways without data (see RUMBO.md)"],
                    ["Ceiling if EVERYTHING open were closed", f"{techo_todo:.1f} %", "RUMBO.md"]],
                   ["item", "value", "nature"]) +
           f"\n> **The predictions alone do not close the framework.** Confirming them all gives {proy:.1f} %; the remaining "
           f"**{irreducible:.1f} points** do not depend on any prediction but on **reading primary sources and "
           "obtaining pathway data** that nobody has published yet. RUMBO.md ranks them by points. "
           "**The points are simulated with the engine's rule; they are no longer written by hand.**\n\n"
           "## The self-correction, which is real\n\n"
           "When a datum arrives for any of these predictions, the procedure is automatic:\n\n"
           "1. It is added as a parameter or source in `red/stasispath.yaml` (one line).\n"
           "2. The engine recomputes bounds, derived quantities, margins, triangulation and sweeps.\n"
           "3. **If the value falls outside the predicted range, the triangulation flags it as a contradiction** and names "
           "which law of the framework fails — which is exactly what happened with I1 and with the isochoric regime of I5.\n\n"
           "That is self-correction: **the framework does not adjust itself to fit the datum, it names what would have to change.**\n")
    (ROOT / "PROYECCION.md").write_text(doc)
    return dict(med_t=med_t, med_n=med_n, proy=proy, irreducible=irreducible)
