"""StasisPath: course — the framework computes where to grow.

For every open node (secondary source [P], or claim/bound/pathway at [A] or [P]) it simulates IN MEMORY
what would happen if it closed (moved to [V]), repropagates the statuses with the engine's own rule
(a node is never worth more than its weakest dependency) and measures how much the grounding rises.

From that:
  1. a ranking of closures by points gained;
  2. a greedy path: the minimum sequence of closures that reaches the goal set in `rumbo.meta` in the YAML;
  3. for each closure, the action that fulfils it (the node's `cierra` field if present, else the generic one).

Declared limit: this closes NOTHING. It says what to close and what it is worth. A node only rises when
the datum or the source enters the YAML (R2, R5). Output: RUMBO.md. Called by motor.py.
"""
from collections import defaultdict

ACCION = {"fuente": "read the primary source and extract the datum",
          "afirmacion": "datum or primary source for its own dependencies",
          "cota": "narrow the parameters or verify against a primary source",
          "via": "published data for the pathway (scale, window, failure)"}

def _propagar(NODOS, D, RANK, cambios):
    EF = {}
    def ef(n, pila=()):
        if n in EF: return EF[n]
        x = NODOS[n]; e = cambios.get(n, x["e"])
        if x["tipo"] == "prereg":
            EF[n] = e; return e
        for d in x["deps"]:
            if d not in NODOS or NODOS[d]["tipo"] == "param" or d in pila: continue
            ed = ef(d, pila + (n,))
            if RANK[ed] < RANK[e]: e = ed
        EF[n] = e; return e
    for n in NODOS: ef(n)
    for q in D["preguntas"]:
        EF[q] = min((EF[a] for a in D["preguntas"][q]["a"]), key=lambda s: RANK[s])
    return EF

def _total(EF, NODOS, D, COMP, SCORE):
    t = 0.0
    for _, w, tipos, capas in COMP:
        ns = [n for n in EF if NODOS[n]["tipo"] in tipos and
              (capas is None or D["afirmaciones"].get(n, {}).get("capa") in capas)]
        if ns: t += w * sum(SCORE[EF[n]] for n in ns) / len(ns)
    return t

def _accion(n, NODOS, D):
    for sec in ("fuentes", "afirmaciones", "vias", "cotas"):
        if n in D.get(sec, {}) and isinstance(D[sec][n], dict) and D[sec][n].get("cierra"):
            return D[sec][n]["cierra"]
    return ACCION.get(NODOS[n]["tipo"], "—")

def simular(D, NODOS, RANK, SCORE, COMP, nodos):
    """Progress if the given nodes moved to [V]. In memory only."""
    return _total(_propagar(NODOS, D, RANK, {n: "V" for n in nodos}), NODOS, D, COMP, SCORE)

def generar(D, NODOS, RANK, SCORE, COMP, ROOT):
    base = _total(_propagar(NODOS, D, RANK, {}), NODOS, D, COMP, SCORE)
    abiertos = [n for n, x in NODOS.items()
                if x["tipo"] in ("fuente", "afirmacion", "cota", "via") and x["e"] in ("A", "P")]
    gan = {n: _total(_propagar(NODOS, D, RANK, {n: "V"}), NODOS, D, COMP, SCORE) - base for n in abiertos}

    # camino voraz hacia la meta
    meta = float(D.get("rumbo", {}).get("meta", 98.0))
    cambios, actual, camino = {}, base, []
    while actual < meta - 1e-9:
        mejor, mg = None, 0.0
        for n in abiertos:
            if n in cambios: continue
            c = dict(cambios); c[n] = "V"
            g = _total(_propagar(NODOS, D, RANK, c), NODOS, D, COMP, SCORE) - actual
            if g > mg + 1e-12: mejor, mg = n, g
        if mejor is None:
            # no isolated closure raises it: look for the PAIR that raises most (one holds the other)
            resto = [n for n in abiertos if n not in cambios]
            par, pg = None, 0.0
            for i, n1 in enumerate(resto):
                for n2 in resto[i + 1:]:
                    c = dict(cambios); c[n1] = "V"; c[n2] = "V"
                    g = _total(_propagar(NODOS, D, RANK, c), NODOS, D, COMP, SCORE) - actual
                    if g > pg + 1e-12: par, pg = (n1, n2), g
            if par is None: break
            for n in par: cambios[n] = "V"
            actual += pg
            camino.append((" + ".join(par), pg, actual))
            continue
        cambios[mejor] = "V"; actual += mg
        camino.append((mejor, mg, actual))
    techo = _total(_propagar(NODOS, D, RANK, {n: "V" for n in abiertos}), NODOS, D, COMP, SCORE)

    def fila(n, g):
        x = NODOS[n]
        return [n, {"afirmacion": "claim", "cota": "bound", "via": "pathway", "pregunta": "question", "prereg": "preregistration"}.get(x["tipo"], x["tipo"]), x["e"], f"+{g:.2f}", _accion(n, NODOS, D)]
    tab = lambda filas, cab: ("| " + " | ".join(cab) + " |\n|" + "---|" * len(cab) + "\n" +
                              "\n".join("| " + " | ".join(str(c) for c in f) + " |" for f in filas) + "\n")
    rank = sorted(((n, g) for n, g in gan.items() if g > 0.005), key=lambda t: -t[1])
    solos = sum(1 for g in gan.values() if g <= 0.005)
    doc = ("<!-- AUTO-GENERATED by red/rumbo.py. DO NOT EDIT BY HAND. -->\n"
           "# StasisPath: course — what to close, in what order, and what it is worth\n\n"
           f"**Current grounding: {base:.1f} %. Goal set in the YAML (`rumbo.meta`): {meta:.1f} %.**\n\n"
           "The framework simulates in memory the closure of every open node and repropagates the statuses with the engine's rule. "
           "**It closes nothing**: a node only rises when its datum or its source enters `red/stasispath.yaml`.\n\n"
           f"- **Ceiling if EVERYTHING open were closed:** {techo:.1f} %. What lies above that does not depend on open nodes, "
           "but on questions or branches nobody has measured.\n"
           f"- **Minimum path to the goal:** {len(camino)} closures take it from {base:.1f} % to {actual:.1f} %"
           + (" (meta alcanzada)." if actual >= meta - 1e-9 else f" and there it runs out: the goal of {meta:.1f} % is **not reachable** by closing open nodes.") + "\n"
           f"- {solos} open nodes **do not raise the total on their own** (a weaker node holds them down). "
           "That is why the order matters.\n\n"
           "## Greedy path (at each step, the closure that gains most given what is already done)\n\n"
           + tab([[i + 1, n, " + ".join(NODOS[k]["tipo"] for k in n.split(" + ")),
                   " + ".join(NODOS[k]["e"] for k in n.split(" + ")), f"+{g:.2f}", f"{t:.1f} %",
                   " · ".join(_accion(k, NODOS, D) for k in n.split(" + "))]
                  for i, (n, g, t) in enumerate(camino)],
                 ["#", "node", "type", "status", "gain", "cumulative", "what closes it"])
           + "\n## Individual ranking (each node closed alone)\n\n"
           + tab([fila(n, g) for n, g in rank], ["node", "type", "status", "gain alone", "what closes it"]))
    (ROOT / "RUMBO.md").write_text(doc)
    sim = lambda nodos: simular(D, NODOS, RANK, SCORE, COMP, nodos)
    return {"base": base, "techo": techo, "camino": camino, "meta": meta, "final": actual, "gan": gan, "simular": sim}
